name: Build Tauri Windows App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Install frontend dependencies
        run: pnpm install

      # Optional: setup MSVC build tools if needed
      - uses: microsoft/setup-msbuild@v1.3.1

      - name: Build the Tauri App
        run: pnpm tauri build

      - name: Upload built .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-build
          path: |
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.exe
